### PR TITLE
Add IE detection and deprecation message

### LINKED ISSUE #209: Add warning and disable app if running in IE
The BC Govt has several alternatives to IE. The federal govt has Chrome at least. Other clients are unlikely to be confined to IE. Elk shows no IE (or Edge) clients hitting our services in the last 3 months. 

Therefore we are now officially not supporting IE. We need to add a warning and disable the app if anyone loads it in IE.

### PR DESCRIPTION
**Pull request by rod-glover**
Resolves #209 

Tested against IE, Edge, Chrome, Firefox.

### CODE REVIEW

**Comment by rod-glover** [comment]
[Demo](http://docker-dev01.pcic.uvic.ca:30521/)

**Comment by corviday** [comment]
It all looks normal to me. Do we have a way to test it with IE? I don't think I have access to a Windows system.

**Review by corviday — APPROVED** [review]
Oh whoops, I missed you saying you'd tested it with IE. Looks good, then!

**Comment by rod-glover** [comment]
Thanks. "We" don't have IE (there's no Linux installation), but I have it on my Windows laptop. An annoying test setup, but it was sufficient.

**Pull request merged**
