### PR TITLE
Add About tab

### LINKED ISSUE #51: Add About tab with version number

### PR DESCRIPTION
**Pull request by rod-glover**
Resolves #51 

This PR adds an About tab with a bunch of standard information (largely copied from CE). It includes the app version id, which will be useful when we begin releasing the app to selected clients.

### CODE REVIEW

**Comment by rod-glover** [comment]
[Demo](http://docker-dev01.pcic.uvic.ca:30502/)

**Comment by nikola-rados** [comment]
Great work @rod-glover. I really like how each section is broken down into these single cards, looks really good. 

I only have one comment/question.  The version specified in the `about/plan2adapt` tab appears to be the branch name and the commit hash. Is this how it is intended to work or is it a placeholder until we put in a semver equivalent?

**Comment by rod-glover** [comment]
The "version" is a composite of tags (if any exist) for the commit, the branch name, and the commit SHA, in that order. What you are seeing at the moment is the absence of any tags on the commit (appropriate for dev). This is what we did in CE, but it can be changed at any time to suit us better.

**Comment by corviday** [comment]
Who do we need to credit for the ANUSPLIN dataset? Is it ANU?

@nikola-rados should probably be listed as a team member for updating the rules engine and wrangling data?

**Comment by rod-glover** [comment]
Well spotted both, @corviday . (@nikola-rados , you are too modest!)

**Comment by rod-glover** [comment]
@corviday , NRCAN is the source for the ANUSPLIN dataset, and they are already credited.

**Pull request merged**
